### ISSUE TITLE
Problem launching pack

### ISSUE THREAD

**Issue by jgeekw** [BQZ2/Expanded-MC#3]
I got this error when I attempted to launch the pack.

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:197)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:147)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:147)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	... 3 more
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\jgeek\AppData\Roaming\gdlauncher_next\instances\ExpandedMC\mods\supplementaries-1.20-2.7.21-fabric.jar]: java.util.zip.ZipException: zip END header not found
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
		at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:144)
		... 5 more
	Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\jgeek\AppData\Roaming\gdlauncher_next\instances\ExpandedMC\mods\supplementaries-1.20-2.7.21-fabric.jar]: java.util.zip.ZipException: zip END header not found
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:288)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237)
		at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
	Caused by: java.util.zip.ZipException: zip END header not found
		at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
		at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
		at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
		at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
		at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
		at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
		at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
		at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:309)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278)
		... 7 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\jgeek\AppData\Roaming\gdlauncher_next\instances\ExpandedMC\mods\moremobvariants-fabric+1.20-1.2.2.jar]: java.util.zip.ZipException: zip END header not found
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:144)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\jgeek\AppData\Roaming\gdlauncher_next\instances\ExpandedMC\mods\moremobvariants-fabric+1.20-1.2.2.jar]: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:288)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237)
	at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:309)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278)
	... 7 more

**Comment by BQZ2** [comment]
Restart you're pc, if that didnt fix it then try to launch the pack with [ATlauncher](https://atlauncher.com/)
